### ISSUE TITLE
Crash on 2.4.3

### ISSUE THREAD

**Issue by alagatar** [tapdaq/tapdaq-android-sdk#1]
```
E/TAPDAQ: Something went wrong while getting advertisement id!
java.lang.NoClassDefFoundError: com.google.android.gms.ads.identifier.AdvertisingIdClient
at com.tapdaq.sdk.TapdaqHelper.getAdvertisementId(TapdaqHelper.java:165)
at com.tapdaq.sdk.TapdaqInitializerRunnable.run(TapdaqInitializerRunnable.java:35)
at java.lang.Thread.run(Thread.java:841)
```

**Comment by alagatar** [comment]
I found that for fixing this needed add to **build.gradle**
```
dependencies {
    compile 'com.android.support:support-v4:24.0.0'
    compile 'com.google.android.gms:play-services:9.0.2'
}
```
Check is this real fix or maybe this is no needed and need some little fixe in lib. If it needed please add this to help page.
Thanks.

**Comment by rdominic** [comment]
Hi,

Correct, this was missing from the documentation, I've added it to the [QuickStart](https://github.com/tapdaq/tapdaq-android-sdk/wiki/Quickstart) page along with some other minor prerequisites.

You can also do a little better, to use the SDK you will only need the Google Play Services Ads component, so rather than including all services you can slim it down to just this:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.google.android.gms:play-services-ads:9.2.0'
}
```

If you need any further help with TapDaq integration, please let us know.

Thanks,
Dominic
